# Generated by Django 4.2.16 on 2026-10-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0012_rename_index_softwaretreenode_tree_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportaggregate',
            old_name='shared_proportion_threshold',
            new_name='_shared_proportion_threshold',
        ),
    ]
